# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58b6d4fe4a03acda216ab2219cf8368ea4d117366dcdd285ff0802fbd54eb00792d1e4d9a52c3ab844fbf9416e7203bb91c0ef377fab217b71d1b6944f023ff7

test:
  secret_key_base: 8f5783676fd19428247ce941e6e0ec140b86c33f21eeb044e325986b46f86771dc3cc38d3950c10718d5e49e6f3f8677fbaeee80713ea568ee929053fd918c13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
